version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: restaurant-website
    ports:
      - "8080:80"
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:80/"]
      interval: 30s
      timeout: 3s
      retries: 3
    networks:
      - restaurant-network

networks:
  restaurant-network:
    driver: bridge
